#ifndef TOKENS_H
#define TOKENS_H

typedef enum {
    TOKEN_EOF = 0,
    TOKEN_BIT,
    TOKEN_IDENT,
    TOKEN_ASSIGN_OP,
    TOKEN_OR_OP,
    TOKEN_AND_OP,
    TOKEN_NOT_OP,
    TOKEN_OPEN_PAR,
    TOKEN_CLOSE_PAR,
    TOKEN_OPEN_TAG,
    TOKEN_CLOSE_TAG,
    TOKEN_OPEN_BRACE,
    TOKEN_CLOSE_BRACE,
    TOKEN_IN_OP,
    TOKEN_OUT_OP,
    TOKEN_COMMA,
    TOKEN_NEWLINE,
    TOKEN_EPSILON,
    TOKEN_ERROR
} TOKEN;

#endif // TOKENS_H
